export const PERSONAL_INFO = {
  name: "Rohan Das",
  title: "Business Analytics & Data Science Professional",
  tagline: "Results-driven MBA candidate specializing in transforming complex data into strategic insights through machine learning, advanced analytics, and compelling visualizations.",
  email: "rohandas943@gmail.com",
  location: "Kolkata, India",
  github: "https://github.com/rohandas56",
  linkedin: "https://www.linkedin.com/in/rohan-das-data-analyst-trainee",
  kaggle: "https://www.kaggle.com/rohandas77",
  credly: "https://www.credly.com/users/rohan-das.99bc0927/badges",
};

export const PROJECTS = [
  {
    id: 1,
    title: "Global Trends in Atmosphere",
    description: "Comprehensive analysis of global atmospheric data patterns and trends using advanced data visualization and statistical modeling techniques.",
    tech: ["Python", "Data Visualization", "Statistical Analysis", "Pandas"],
    github: "https://github.com/rohandas56/Food_Delivery_time_prediction",
    kaggle: "https://www.kaggle.com/code/rohandas77/global-trends-in-atmosphere",
    category: "Environmental Analytics",
    gradient: "from-green-400 to-blue-500",
  },
  {
    id: 2,
    title: "Cinema Hall Ticket Sales EDA",
    description: "Exploratory data analysis of cinema ticket sales patterns, revenue optimization, and customer behavior insights for entertainment industry.",
    tech: ["Python", "EDA", "Business Intelligence", "Matplotlib"],
    github: "https://github.com/rohandas56/Iris_data_model",
    kaggle: "https://www.kaggle.com/code/rohandas77/cinema-hall-ticket-sales-eda",
    category: "Business Analytics",
    gradient: "from-purple-400 to-pink-500",
  },
  {
    id: 3,
    title: "ML & Data Science Survey 2022",
    description: "Comprehensive analysis of machine learning and data science industry trends, salary insights, and technology adoption patterns.",
    tech: ["Python", "Survey Analysis", "Data Science", "Seaborn"],
    github: "https://github.com/rohandas56/Project_2",
    kaggle: "https://www.kaggle.com/code/rohandas77/ml-and-ds-survey-2022-by-rohan",
    category: "Industry Research",
    gradient: "from-orange-400 to-red-500",
  },
  {
    id: 4,
    title: "Fraud Transactions Detection",
    description: "Advanced fraud detection system using machine learning algorithms to identify suspicious financial transactions and prevent losses.",
    tech: ["Python", "Machine Learning", "Fraud Detection", "Classification"],
    github: "https://github.com/rohandas56/Food_Delivery_time_prediction",
    kaggle: "https://www.kaggle.com/code/rohandas77/fraud-transactions-eda-and-model-building",
    category: "Financial Analytics",
    gradient: "from-red-400 to-yellow-500",
  },
  {
    id: 5,
    title: "ASL Recognition Deep Learning",
    description: "Deep learning model for American Sign Language recognition using computer vision and neural networks for accessibility applications.",
    tech: ["Python", "Deep Learning", "Computer Vision", "TensorFlow"],
    github: "https://github.com/rohandas56/Ml-Project",
    kaggle: "https://www.kaggle.com/code/rohandas77/asl-recognition-deep-learning-model",
    category: "Computer Vision",
    gradient: "from-blue-400 to-purple-500",
  },
];

export const IBM_CERTIFICATIONS = [
  { name: "Hadoop Programming - Level 1", date: "Jun 28, 2025" },
  { name: "Containers & Kubernetes Essentials", date: "Jun 25, 2025" },
  { name: "Data Science for Business - Level 1", date: "Jun 20, 2025" },
  { name: "Intermediate Kubernetes Operators", date: "Jun 20, 2025" },
  { name: "Accelerated Deep Learning with GPU", date: "May 8, 2025" },
  { name: "Cloud Essentials", date: "May 8, 2025" },
  { name: "Deep Learning using TensorFlow", date: "May 8, 2025" },
  { name: "Docker Essentials: A Developer Introduction", date: "May 8, 2025" },
  { name: "Spark - Level 1", date: "May 8, 2025" },
  { name: "Big Data Foundations - Level 1", date: "Apr 25, 2024" },
  { name: "Build Your Own Chatbot - Level 1", date: "Apr 25, 2024" },
  { name: "Hadoop Foundations - Level 1", date: "Apr 25, 2024" },
  { name: "Using R with Databases", date: "Apr 25, 2024" },
  { name: "Data Visualization with R", date: "Apr 21, 2024" },
  { name: "Python for Data Science", date: "Apr 21, 2024" },
  { name: "Machine Learning with Python - Level 1", date: "Mar 18, 2024" },
  { name: "Statistics 101", date: "Mar 11, 2024" },
];

export const SKILLS = {
  technical: [
    { name: "Python", icon: "fab fa-python" },
    { name: "SQL", icon: "fas fa-database" },
    { name: "Power BI", icon: "fas fa-chart-bar" },
    { name: "Tableau", icon: "fas fa-chart-line" },
  ],
  expertise: [
    { name: "Machine Learning", icon: "fas fa-brain" },
    { name: "Data Analytics", icon: "fas fa-chart-pie" },
    { name: "Data Visualization", icon: "fas fa-eye" },
    { name: "Business Intelligence", icon: "fas fa-cogs" },
  ],
};
